### ISSUE TITLE
Can't route multiple inputs to same phase in new-experiment format?

### ISSUE THREAD

**Issue by dstockwell** [dglazkov/tree-builder-builder#100]
This didn't work:

```
digraph trace {

  subgraph cluster0 {
    fileToBuffer -> gunzipAndDecode -> jsonParse -> traceFilter -> tracePIDSplitter -> traceTIDSplitter -> traceTree;
    traceTree -> tracePrettyPrint;

    tracePrettyPrint -> toTag -> consoleOutput;
    toTag [tag="filename"]

    tracePrettyPrint -> consoleOutput;

    color=blue;
    strategy=pipeline;
  }

  input [data="/somewhere"]
  input -> readDir -> fileToBuffer;

  consoleOutput -> dummy;
  dummy [label="input"]


  traceFilter [traceEvents="['Document::updateStyle','V8.Execute','CSSParserImpl::parseStyleSheet']"];

  tracePrettyPrint [showTrace="false"];
}
```

Failed with:

```
TypeError: Cannot call method 'split' of undefined
    at Object.stageSpecificationToStage (/usr/local/google/ssd/repos/tree-builder-builder/core/stage-loader.js:47:20)
    at /usr/local/google/ssd/repos/tree-builder-builder/core/new-experiment.js:77:40
    at Array.map (native)
    at Object.impl (/usr/local/google/ssd/repos/tree-builder-builder/core/new-experiment.js:76:33)
    at /usr/local/google/ssd/repos/tree-builder-builder/core/stage-loader.js:92:19
    at /usr/local/google/ssd/repos/tree-builder-builder/core/stages.js:56:5
    at fs.js:258:14
    at /usr/local/google/ssd/repos/tree-builder-builder/node_modules/mocha/node_modules/glob/node_modules/graceful-fs/graceful-fs.js:104:5
    at Object.oncomplete (fs.js:97:15)
```

**Comment by shans** [comment]
I *think* this is fixed now.
